/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "USB.h"
#include "USB_audio.h"
#include "USB_cdc.h"
#include "USB_hid.h"
#include "USB_midi.h"
#include "USB_pvt.h"
#include "USB_cydmac.h"
#include "USB_msc.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "Pin_3_aliases.h"
#include "Pin_3.h"
#include "Pin_4_aliases.h"
#include "Pin_4.h"
#include "Pin_5_aliases.h"
#include "Pin_5.h"
#include "Pin_6_aliases.h"
#include "Pin_6.h"
#include "Pin_7_aliases.h"
#include "Pin_7.h"
#include "Pin_8_aliases.h"
#include "Pin_8.h"
#include "Pin_9_aliases.h"
#include "Pin_9.h"
#include "LCD.h"
#include "UART.h"
#include "rx_int.h"
#include "TX_aliases.h"
#include "TX.h"
#include "tx_int.h"
#include "USB_Dm_aliases.h"
#include "USB_Dm.h"
#include "USB_Dp_aliases.h"
#include "USB_Dp.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

